### ISSUE TITLE
Parser crashed in case of a single spouse in a family record

### ISSUE THREAD

**Issue by ligurio** [iand/gedcom#4]
Example of Golang source to reproduce bug:
```
package main

import (
        "bytes"
        "github.com/iand/gedcom"
        "io/ioutil"
)

func main() {
        data, _ := ioutil.ReadFile("fam.ged")
        d := gedcom.NewDecoder(bytes.NewReader(data))
        g, _ := d.Decode()

        for _, rec := range g.Family {
                println(rec.Xref, rec.Husband.Xref, rec.Wife.Xref)
        }
}
```

Sample of GEDCOM file (fam.ged):

```
0 @F4@ FAM
1 HUSB @I2@
1 MARR
2 DATE
0 @I2@ INDI
1 NAME Man
1 SEX F
0 @I3@ INDI
1 NAME Woman
1 SEX M
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x21c0]

goroutine 1 [running]:
panic(0xb42c0, 0xc42000a1b0)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
        /Users/sergeyb/source/gopath/src/github.com/ligurio/gedcom2sql/repro.go:25 +0x180
```

**Comment by iand** [comment]
Sorry it's taken so long to respond to this. I don't think this is an bug. The panic occurs because you are calling `.Husband.Xref` on a family record that does not have an entry for the husband. The husband field is `nil` to represent an unknown value.
